# FullSubNet_plus/config/config.yaml

audio:
  n_fft: 512
  win_length: 512
  hop_length: 256
  sr: 16000
  batch_size: 8
  num_workers: 4



pre_trained_data_model:
  data_path: "C:/Kfir/repos/generative-audio/FullSubNet_plus/data/clean"
  enhanced_dir_path: "C:/Kfir/repos/generative-audio/FullSubNet_plus/data/enhanced2"
  dataset:
    clean_path: "C:/Kfir/repos/generative-audio/FullSubNet_plus/data/clean"
    noisy_path: "C:/Kfir/repos/generative-audio/FullSubNet_plus/data/noisy"



pre_trained_model:
  checkpoint_path: "C:/Kfir/repos/generative-audio/FullSubNet_plus/best_model.tar"
  #checkpoint_path: "../../../FullSubNet_plus/best_model.tar"
  device: "cpu"
  model:
    sb_num_neighbors: 15
    fb_num_neighbors: 0
    num_freqs: 257
    look_ahead: 2
    sequence_model: "LSTM"
    fb_output_activate_function: "ReLU"
    sb_output_activate_function: false
    channel_attention_model: "TSSE"
    fb_model_hidden_size: 512
    sb_model_hidden_size: 384
    weight_init: false
    norm_type: "offline_laplace_norm"
    num_groups_in_drop_band: 1
    kersize: [3, 5, 10]
    subband_num: 1