

model_validator_configuration:
  model_configuration:
    in_channels: 1
    out_channels: 1
#    channels_list: [64, 128, 256, 512]
#    bottleneck_channels: 512
#    min_channels_decoder: 64
#    n_groups: 8
  checkpoint_path: "../../../../../../data/inpainting/restoration_model/checkpoint/checkpoint_final_20250118_010156.pt"
#  checkpoint_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250111_010610.pt"

  device: "cuda"
  save_dir: "validation_results"



data_configuration:
  clean_path: "../../../../../../data/clean/train"
  sample_rate: 16000
  missing_length_seconds: 0.256
  missing_start_seconds: 0.4
  # Adjust the sub_sample_length_seconds to get exactly T=512:
  sub_sample_length_seconds: 1.022
  target_dB_FS: -25.0
  stft_configuration:
    # nfft chosen to yield F=256
    nfft: 255
    win_length: 255
    hop_length: 128
  use_vad: True

dataloader_configuration:
  batch_size: 1
  shuffle: true
  num_workers: 4
  pin_memory: true