

model_validator_configuration:
  model_configuration:
    in_channels: 2
    out_channels: 2
    channels_list: [32, 64, 128, 256]
    bottleneck_channels: 512
    min_channels_decoder: 64
    n_groups: 8
  checkpoint_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20241221_235416.pt"
  device: "cuda"
  save_dir: "validation_results"



data_configuration:
  clean_path: "../../../../FullSubNet_plus/data/clean/test"
  sample_rate: 16000
  missing_length_seconds: 0.5
  missing_start_seconds: 3
  # Adjust the sub_sample_length_seconds to get exactly T=512:
  sub_sample_length_seconds: 8.176
  target_dB_FS: -25.0
  stft_configuration:
    # nfft chosen to yield F=256
    nfft: 510
    win_length: 510
    hop_length: 256

dataloader_configuration:
  batch_size: 16
  shuffle: true
  num_workers: 4
  pin_memory: true