

clean_wav_path: "../../../FullSubNet_plus/data/output/clean_snr_-15/sample_0000_clean.wav"
noisy_wav_path: "../../../FullSubNet_plus/data/output/noisy_snr_-15/sample_0000_noisy.wav"
save_dir: "../../../FullSubNet_plus/data/results"
nppc_audio_validator_configuration:
#  checkpoint_path: "../checkpoints/checkpoint_final_20241212_160930.pt"
  checkpoint_path: "../checkpoints/checkpoint_final_20241214_000943.pt"

  nppc_audio_model_configuration:
    device: "cuda"
    stft_configuration:
      nfft: 512
      win_length: 512
      hop_length: 256
    pretrained_restoration_model_path: "../../../FullSubNet_plus/best_model.tar"
    pretrained_restoration_model_configuration:
      sb_num_neighbors: 15
      fb_num_neighbors: 0
      num_freqs: 257
      look_ahead: 2
      sequence_model: "LSTM"
      fb_output_activate_function: "ReLU"
      sb_output_activate_function: false
      channel_attention_model: "TSSE"
      fb_model_hidden_size: 512
      sb_model_hidden_size: 384
      weight_init: false
      norm_type: "offline_laplace_norm"
      num_groups_in_drop_band: 1
      kersize: [ 3, 5, 10 ]
      subband_num: 1
    audio_pc_wrapper_configuration:
      multi_direction_configuration:
        n_directions: 5
        sb_num_neighbors: 15
        fb_num_neighbors: 0
        num_freqs: 257
        look_ahead: 2
        sequence_model: "LSTM"
        fb_output_activate_function: "ReLU"
        sb_output_activate_function: false
        channel_attention_model: "TSSE"
        fb_model_hidden_size: 512
        sb_model_hidden_size: 384
        weight_init: false
        norm_type: "offline_laplace_norm"
        num_groups_in_drop_band: 1
        kersize: [ 3, 5, 10 ]
        subband_num: 1


