n_epochs: 5
checkpoint_dir: "../../../../FullSubNet_plus/data/inpainting/nppc_model/checkpoint"
inpainting_nppc_training_configuration:
  device: "cuda"
  second_moment_loss_lambda: 1
  nppc_model_configuration:
    pretrained_restoration_model_configuration:
      in_channels: 1
      out_channels: 1
#    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250104_122437.pt"
#    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250101_202345.pt"
#    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250104_194616.pt"
#    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250105_201001.pt"
    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250106_005716.pt"


    audio_pc_wrapper_configuration:
      n_dirs: 64
      model_configuration:
        in_channels: 2
        out_channels: 64
    device: "cuda"



  data_configuration:
    clean_path: "../../../../FullSubNet_plus/data/clean/train"
    sample_rate: 16000
    missing_length_seconds: 0.1
    missing_start_seconds: 0.128
    # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
    sub_sample_length_seconds: 0.2555
    target_dB_FS: -25.0
    stft_configuration:
      nfft: 127
      win_length: 127
      hop_length: 64

  dataloader_configuration:
    batch_size: 128
    shuffle: true
    num_workers: 16
    pin_memory: false

  optimizer_configuration:
    type: "Adam"
    args:
      lr: 1.0e-4
      betas: [0.5, 0.999]





validation_data_configuration:
  clean_path: "../../../../FullSubNet_plus/data/clean/test"
  sample_rate: 16000
  missing_length_seconds: 0.128
  missing_start_seconds: 0.1
  # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
  sub_sample_length_seconds: 0.2555
  target_dB_FS: -25.0
  stft_configuration:
    nfft: 127
    win_length: 127
    hop_length: 64