# Configuration for audio inpainting training
#n_steps: 2000
n_epochs: 16
checkpoint_dir: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint"
inpainting_training_configuration:
  device: "cuda"
  model_configuration:
    in_channels: 1
    out_channels: 1
#    base_channels: 64
#    base_filters: 64
#    channels_list: [32, 64, 128, 256]
#    bottleneck_channels: 512
#    min_channels_decoder: 64
#    n_groups: 8


  data_configuration:
    clean_path: "../../../../FullSubNet_plus/data/clean/train"
    sample_rate: 16000
    missing_length_seconds: 0.128
    missing_start_seconds: 0.4
    # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
    sub_sample_length_seconds: 1.022
    target_dB_FS: -25.0
    stft_configuration:
      # nfft chosen to yield F=256
#      nfft: 510
#      win_length: 510
#      hop_length: 256
      nfft: 255
      win_length: 255
      hop_length: 128

  dataloader_configuration:
    batch_size: 64
    shuffle: true
    num_workers: 64
    pin_memory: false

  optimizer_configuration:
    type: "Adam"
    args:
      lr: 1.0e-5
      betas: [0.5, 0.999]




validation_data_configuration:
  clean_path: "../../../../FullSubNet_plus/data/clean/test"
  sample_rate: 16000
  missing_length_seconds: 0.128
  missing_start_seconds: 0.4
  # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
  sub_sample_length_seconds: 1.022
  target_dB_FS: -25.0
  stft_configuration:
    # nfft chosen to yield F=256
#      nfft: 510
#      win_length: 510
#      hop_length: 256
    nfft: 255
    win_length: 255
    hop_length: 128