# Configuration for audio inpainting training
#n_steps: 2000
n_epochs: 10
checkpoint_dir: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint"
inpainting_training_configuration:
  device: "cuda"
  model_configuration:
    in_channels: 1
    out_channels: 1



  data_configuration:
    clean_path: "../../../../FullSubNet_plus/data/clean/train"
    sample_rate: 16000
    missing_length_seconds: 0.128
    missing_start_seconds: 0.1
    # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
    sub_sample_length_seconds: 0.2555
    target_dB_FS: -25.0
    stft_configuration:
      nfft: 127
      win_length: 127
      hop_length: 64

  dataloader_configuration:
    batch_size: 64
    shuffle: true
    num_workers: 16
    pin_memory: false

  optimizer_configuration:
    type: "Adam"
    args:
      lr: 1.0e-5
      betas: [0.5, 0.999]




validation_data_configuration:
  clean_path: "../../../../FullSubNet_plus/data/clean/test"
  sample_rate: 16000
  missing_length_seconds: 0.128
  missing_start_seconds: 0.1
  # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
  sub_sample_length_seconds: 0.2555
  target_dB_FS: -25.0
  stft_configuration:
    nfft: 127
    win_length: 127
    hop_length: 64