# Configuration for audio inpainting training
#n_steps: 2000
n_epochs: 8
#checkpoint_dir: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint"
checkpoint_dir: "../../../../../../data/inpainting/restoration_model/checkpoint"
inpainting_training_configuration:
  device: "cuda"
  model_configuration:
    in_channels: 1
    out_channels: 1



  data_configuration:
#    clean_path: "../../../../FullSubNet_plus/data/clean/train"
    clean_path: "../../../../../../data/clean/train"
    sample_rate: 16000
    missing_length_seconds: 0.256
    missing_start_seconds: 0.4
    # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
    sub_sample_length_seconds: 1.022
    target_dB_FS: -25.0
    stft_configuration:
      nfft: 255
      win_length: 255
      hop_length: 128
    use_vad: True

  dataloader_configuration:
    batch_size: 128
    shuffle: true
    num_workers: 32
    pin_memory: false

  optimizer_configuration:
    type: "Adam"
    args:
      lr: 1.0e-4
      betas: [0.5, 0.999]




#validation_data_configuration:
#  clean_path: "../../../../../../data/clean/test"
#  sample_rate: 16000
#  missing_length_seconds: 0.256
#  missing_start_seconds: 0.4
#  # Adjust the sub_sample_length_seconds to get exactly T=512:
##    sub_sample_length_seconds: 8.176
##    sub_sample_length_seconds: 4.088
#  sub_sample_length_seconds: 1.022
#  target_dB_FS: -25.0
#  stft_configuration:
#    nfft: 255
#    win_length: 255
#    hop_length: 128
#  use_vad: True
