n_epochs: 10
checkpoint_dir: "../../../../FullSubNet_plus/data/inpainting/nppc_model/checkpoint"
inpainting_nppc_training_configuration:
  device: "cuda"
  nppc_model_configuration:
    pretrained_restoration_model_configuration:
      in_channels: 1
      out_channels: 1
    pretrained_restoration_model_path: "../../../../FullSubNet_plus/data/inpainting/restoration_model/checkpoint/checkpoint_final_20250101_202345.pt"
    audio_pc_wrapper_configuration:
      n_dirs: 5
      model_configuration:
        in_channels: 2
        out_channels: 5
    device: "cuda"



  data_configuration:
    clean_path: "../../../../FullSubNet_plus/data/clean/train"
    sample_rate: 16000
    missing_length_seconds: 0.128
    missing_start_seconds: 0.4
    # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
    sub_sample_length_seconds: 1.022
    target_dB_FS: -25.0
    stft_configuration:
      nfft: 255
      win_length: 255
      hop_length: 128

  dataloader_configuration:
    batch_size: 64
    shuffle: true
    num_workers: 64
    pin_memory: false

  optimizer_configuration:
    type: "Adam"
    args:
      lr: 1.0e-5
      betas: [0.5, 0.999]





validation_data_configuration:
  clean_path: "../../../../FullSubNet_plus/data/clean/test"
  sample_rate: 16000
  missing_length_seconds: 0.128
  missing_start_seconds: 0.4
  # Adjust the sub_sample_length_seconds to get exactly T=512:
#    sub_sample_length_seconds: 8.176
#    sub_sample_length_seconds: 4.088
  sub_sample_length_seconds: 1.022
  target_dB_FS: -25.0
  stft_configuration:
    nfft: 255
    win_length: 255
    hop_length: 128